### ISSUE TITLE
how can i use it wihout load !

### ISSUE THREAD

**Issue by Brushez** [mkrogh/svg-png#1]
i want to use an exist svg inside div html ?

**Comment by mkrogh** [comment]
Hmm not sure what you are asking, but you can use svg directly in your html with most modern browsers.

See e.g. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg 

This little repository was made for converting SVGs to PNGs using your browser's svg renderer. This is also know as rasterisation.
